### ISSUE TITLE
File "/usr/local/lib/python3.5/dist-packages/mpu/datastructures/trie/char_trie.py", line 16

### ISSUE THREAD

**Issue by mathewatspm** [MartinThoma/mpu#74]
Affected `mpu` version: 0.23.0
```
$ cfg_load   test.json 
Traceback (most recent call last):
  File "/usr/local/bin/cfg_load", line 10, in <module>
    import cfg_load
  File "/usr/local/lib/python3.5/dist-packages/cfg_load/__init__.py", line 19, in <module>
    from mpu.datastructures import dict_merge, set_dict_value
  File "/usr/local/lib/python3.5/dist-packages/mpu/__init__.py", line 11, in <module>
    from mpu import io, shell, string, units  # noqa
  File "/usr/local/lib/python3.5/dist-packages/mpu/io.py", line 18, in <module>
    from mpu.datastructures import EList
  File "/usr/local/lib/python3.5/dist-packages/mpu/datastructures/__init__.py", line 11, in <module>
    from mpu.datastructures.trie import Trie  # noqa
  File "/usr/local/lib/python3.5/dist-packages/mpu/datastructures/trie/__init__.py", line 26, in <module>
    from mpu.datastructures.trie.char_trie import Trie as CharTrie  # noqa
  File "/usr/local/lib/python3.5/dist-packages/mpu/datastructures/trie/char_trie.py", line 16
    self.children: Dict[str, TrieNode] = children
                 ^
SyntaxError: invalid syntax
```

`mpu` version 0.20.0 works fine.
`cfg-load` version: 0.8.0
`python` version: 3.5.3

**Comment by MartinThoma** [comment]
This is expected, as I only support Python 3.6+: https://github.com/MartinThoma/mpu/blob/master/setup.cfg#L35

However, I've just noticed that https://github.com/MartinThoma/mpu/blob/master/setup.cfg#L43 needs to be udpated

**Comment by MartinThoma** [comment]
Thank you for reporting this issue, @mathewatspm . I've now denoted properly that only Python 3.6+ is supported.
