### ISSUE TITLE
currencies.csv is not properly copied

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/mpu#9]
```
python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpu.units
>>> mpu.units.get_currency('de')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/math/.local/lib/python3.5/site-packages/mpu/units/__init__.py", line 146, in get_currency
    with open(filepath, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/math/.local/lib/python3.5/site-packages/mpu/units/currencies.csv'
```

**Comment by MartinThoma** [comment]
http://python-packaging.readthedocs.io/en/latest/non-code-files.html

**Comment by MartinThoma** [comment]
https://stackoverflow.com/q/49698077/562769 could be solved by the units package

**Comment by MartinThoma** [comment]
Fixed in https://github.com/MartinThoma/mpu/commit/1a80c74f9e5bc79ded1d95ae5833b23e45ed7430
